### ISSUE TITLE
Compatibility with BCEWithLogitsLoss

### ISSUE THREAD

**Issue by zifeo** [dnouri/skorch#137]
`BCEWithLogitsLoss` expects a target of size = n, 1. However the underlying tensor seems to be squeezed somewhere.

```python
import numpy as np
from sklearn.datasets import make_classification
from torch import nn

from skorch.net import NeuralNetClassifier


X, y = make_classification(1000, 20, n_classes=2, n_informative=10, random_state=0)
X = X.astype(np.float32)
y = y.astype(np.float32).reshape(-1, 1)

class Dummy(nn.Module):
    def __init__(self):
        super().__init__()
        self.dense = nn.Linear(20, 1)
    
    def forward(self, X):
        return self.dense(X)
    
net = NeuralNetClassifier(
    Dummy,
    criterion=nn.BCEWithLogitsLoss,
)

net.fit(X, y) 
# ValueError: Target size (torch.Size([128])) must be the same as input size (torch.Size([128, 1]))
```

**Comment by BenjaminBossan** [comment]
Indeed we squeeze the outgoing vector in the `NeuralNetClassifier`. This is a current workaround whose intent is explained here: https://github.com/dnouri/skorch/blob/master/skorch/net.py#L1138

This is also the method you could override if you want to circumvent the squeeze.

Alternatively, you could use `NeuralNet` (not the classifier) or you could use `NLLLoss` with softmax nonlinearity (with the caveats that apply there).

**Comment by zifeo** [comment]
Subclassing directly `NeuralNet` works fine, thanks. Although I could not reproduce the issue you mentioned, I'm happy to look for an eventual solution. Related #65.

> I see no solution that would result in a 1-dim LongTensor after passing through torch's DataLoader

**Comment by ottonemo** [comment]
We are not going to support `BCELoss` in `NeuralNetClassifier` as it is structurally very different to the multi-class case. We will, however, provide a `NeuralNetBinaryClassifier` class for convenience. In the mean time, as already suggested, using `NeuralNet` directly works fine.

**Comment by ottonemo** [comment]
Closing in favor of #200.
