### ISSUE TITLE
Feature: Add on_grad_computed to callbacks

### ISSUE THREAD

**Issue by BenjaminBossan** [dnouri/skorch#139]
The idea is that things like grad clipping/norm should be moved to a callback method. This prevents clutter like here:

https://github.com/dnouri/skorch/blob/master/skorch/net.py#L493

Furthermore, it is more flexible, users can extend things more easily.

The API would probably be:

```
def train_step(...):
    ...
    loss.backward()
    self.notify('on_grad_computed', parameters=self.module_.parameters())
    self.optimizer_.step()
```

We have to make it easy to extend this in case that there is more than one backward pass per batch.

**Comment by ottonemo** [comment]
Resolved by #140.
