### ISSUE TITLE
train_batch_size wrong in history with multi X inputs

### ISSUE THREAD

**Issue by loic001** [dnouri/skorch#142]
Hey, thanks for your lib, skorch is cool !

https://github.com/dnouri/skorch/blob/master/skorch/net.py
line 566
`                self.history.record_batch('train_batch_size', len(Xi))
`
len(Xi) does not return correct batch size if Xi is a dict
`
Xi = { 'x': <FloatTensor> }
`

**Comment by ottonemo** [comment]
Thanks for the report, this is indeed a bug. We'll fix it ASAP.
