### ISSUE TITLE
Make sure that disabling callbacks during init is possible 

### ISSUE THREAD

**Issue by ottonemo** [dnouri/skorch#148]
Callbacks, especially those that are set by default, are unnecessarily difficult to remove at the moment. It would be nice to support the same feature that sklearn offers to skip elements in a pipeline for the list of callbacks (setting the respective element to `None`).

Something like this:

    net = NeuralNetClassifier(callbacks__EpochScoring=None)

**Comment by benjamin-work** [comment]
Addressed in #188
