### ISSUE TITLE
fit() parameters when using iterator_train and iterator_valid

### ISSUE THREAD

**Issue by haarburger** [dnouri/skorch#163]
I implemented my own `Dataset` that inherits from `skorch.dataset.Dataset` to apply custom transforms for data augmentation.

As far as I understood the documentation, I need to pass `DataLoader` instances to `NeuralNetClassifier(..., iterator_train, iterator_valid)`. 

How is this supposed to work together with `fit()` since I don't have any numpy arrays `X`, and `y` that I pass to `fit` if I use a custom `Dataset` as explained above.

Thank you in advance!

**Comment by ottonemo** [comment]
This is also addressed in #146, currently it is not possible to pass a dataset to `fit()` but we are working on enabling exactly that. In the meantime you can pass the datasets to the iterator and use dummy values in `fit()`:

     dataset_train = YourTrainDataset()
     dataset_valid = YourValidDataset()

     def iterator_train(dataset, **kwargs):
          return torch.utils.data.DataLoader(dataset_train)

     def iterator_valid(dataset, **kwargs):
          return torch.utils.data.DataLoader(dataset_valid)

     net = NeuralNetClassifier(
         iterator_train=iterator_train,
         iterator_valid=iterator_valid,
     )

     net.fit(np.zeros(len(dataset_train)))

**Comment by ottonemo** [comment]
With the merge of #170 it is possible to use datasets in `fit()`:

    dataset_train = YourTrainDataset()
    dataset_valid = YourValidDataset()

    net = NeuralNetClassifier(
        train_split=lambda ds, _: ds, dataset_valid
    )
    net.fit(dataset_train)
