### ISSUE TITLE
set_params with unknown attribute does not raise

### ISSUE THREAD

**Issue by benjamin-work** [dnouri/skorch#175]
We have an inconsistency with sklearn, namely that calling ~~a `NeuralNet`'s or~~ a `Callback`'s `set_params` with an unknown attribute just sets this attribute. In sklearn, a `ValueError` is raised:

```ValueError: Invalid parameter foo for estimator LogisticRegression. Check the list of available parameters with `estimator.get_params().keys()`.```

**Comment by ottonemo** [comment]
Waiting for an answer @ sklearn.
