### ISSUE TITLE
*Callbacks* A callback that saves the model periodically.

### ISSUE THREAD

**Issue by ottonemo** [dnouri/skorch#18]
Requirements:

- the callback should not only save the weights but also the training parameters (i.e. pickling the learner and using `torch.save` to save the model data)
- option to disable 'best only' checking, we might want to do check-pointing at every epoch

Open questions:

- how much customization do we allow for selecting the 'best' run? Just make the key configurable (e.g. `key='valid_loss_best'`)?
- do we want to provide formatting options for the data path (e.g. `{epoch}` or `{unique_run_id}`)? Might be useful when doing grid search and runs would otherwise override checkpoints

**Comment by benjamin-work** [comment]
Also worth considering:
* Be agnostic about how data is saved (file, blob, etc.)

**Comment by Atry** [comment]
Is there any approach to save parameters in an optimizer?

It seems that only `self. module_` is changed when `load_params`:
https://github.com/dnouri/skorch/blob/00f53ecf9455df702c7fe686e238ac7641567e03/skorch/net.py#L1383

**Comment by ottonemo** [comment]
One can also use pickle to save the state of the net, that way things such as the optimiser are preserved as well. However, the checkpoint callback does not support using pickle at the moment.
