### ISSUE TITLE
Tentative: Explicitely support `device` instead of using `use_cuda` (see http://pytorch.org/docs/stable/tensor_attributes.html#torch-device).

### ISSUE THREAD

**Issue by benjamin-work** [dnouri/skorch#186]
Currently, the user indicates `use_cuda=True/False`. With pytorch 0.4, it is suggested to use `device` instead.

It could be worth to make a breaking change (or transition) that removes `use_cuda` and adds a `device` parameter. If `device=None`, we use:

```
self.device_ = torch.device("cuda" if use_cuda else "cpu")
```

as per the suggestion of the [migration guide](http://pytorch.org/2018/04/22/0_4_0-migration-guide.html).

We should also allow a string to be passed, e.g. 'cpu' or 'cuda'.

The change from `use_cuda` to `device` will probably allow for more diverse backends in the future.

**Comment by ottonemo** [comment]
I suggest to change the name of `location` in `forward` to `device` as well so everything's consistent.
