### ISSUE TITLE
Other torch criterion for NeuralNetClassifier

### ISSUE THREAD

**Issue by shayakhmetov** [dnouri/skorch#197]
`NeuralNetClassifier` can take arbitrary torch criterion, but in its `get_loss` function it computes the logarithm of predicted values, which should be computed for torch.nn.NLLLoss, but not for torch.nn.CrossEntropyLoss, for example. Please make sure that the logarithm is computed only when needed.

**Comment by ottonemo** [comment]
Thank you for reporting this issue. We aware that this is a problem and discussed this in detail in #136. We will most probably fix this in 0.2.
