### ISSUE TITLE
Provide NeuralNetBinaryClassifier

### ISSUE THREAD

**Issue by ottonemo** [dnouri/skorch#200]
While `NeuralNetClassifier` supports binary classification when formulated as a multi-class classification problem with two classes (`shape == (n, 2)`), it does not support modeling the prediction as vector (`shape == (n,)`) and using a threshold (i.e. 0.5) to determine the class (see also: #137).

Since this way of modeling binary classification differs from multi-class in several ways we will not change the existing class to support binary classification but will introduce a new class that can specifically handle all intricacies that may arise in this use-case.

**Comment by 8key** [comment]
Hello, how can I be involved as a contributor, want to add my effort to this great project. thanks

**Comment by BenjaminBossan** [comment]
Hi 8key, we are happy for all contributors. 

Regarding what you could do, it depends a little bit on your skill level and your preferences. In general, you can just make a [pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) and we will review it. We don't have contribution guidelines yet, but your code should adhere to PEP8+pylint style, should be covered by unit tests, and, where applicable, have docstrings and/or documentation entries.

For topics, look at the issue tracker or just think about what you would like to have for yourself. E.g., what can always be improved are the documentation and error messages (try to remember where you first struggled when using skorch).

If you would like to add a new feature that is not in the issues, it is best to ask us first. Then we could give you some guidelines.

**Comment by 8key** [comment]
Hello Ben,

Sounds good, So i will pick some issue to work on to start with then. thanks

Greg
________________________________
