### ISSUE TITLE
Earlystop callback for skorch

### ISSUE THREAD

**Issue by johnny5550822** [dnouri/skorch#205]
Is there any example of showing earlystop callback in skorch?

**Comment by ottonemo** [comment]
@johnny5550822, there is PR #205 now. If you like you can give us feedback if that implementation suits your needs.

**Comment by johnny5550822** [comment]
@ottonemo Awesome, looking forward to it!

**Comment by ottonemo** [comment]
@johnny5550822 You can always check out the corresponding pull request via git or copy the code into your local skorch git repository. See https://github.com/dnouri/skorch#using-conda for instructions.

**Comment by johnny5550822** [comment]
@ottonemo Thanks!
