### ISSUE TITLE
skorch Dataset no longer needs to cast to tensor

### ISSUE THREAD

**Issue by BenjaminBossan** [dnouri/skorch#223]
We probably no longer need to cast to tensor within skorch's `Dataset.transform`, since that is handled elsewhere in `NeuralNet`\*. A quick test seems to indicate that this works and all tests pass. We should think about whether this could cause trouble down the road.

\* The reason why this was once necessary is because the `Dataset` cast to tensor and later data was wrapped into a `Variable` (PyTorch <0.4).

**Comment by taketwo** [comment]
It also does not need the `device` argument anymore, because the correct device is used at the point of conversion in `NeuralNet`*.
