### ISSUE TITLE
How to fine tune a pretrained network?

### ISSUE THREAD

**Issue by Arkoprabho** [dnouri/skorch#236]
I have a ResNet pre-trained model. I am freezing all the layers but the final FC layers. How to set the optimizer such that I can fine tune the network.
On keeping it at the default I get the error:
`ValueError: optimizing a parameter that doesn't require gradients`
which is obvious since the optimizer tries to optimize the parameters which have been marked with `requires_grad=False`.
On creating a custom optimizer with
`optimizer_conv = torch.optim.SGD((filter(lambda p: p.requires_grad, model.parameters())), lr=0.001, momentum=0.9)`
I get the error:
`TypeError: 'SGD' object is not callable`.

**Comment by BenjaminBossan** [comment]
I haven't tried it myself, but I believe that param groups should be able to help you there. Here is an example from the docstring:

```
            optimizer__param_groups=[
                ('rnn*.period', {'lr': 0.3, 'momentum': 0}),
                ('rnn0', {'lr': 0.1}),
            ]
```

By setting the learning rate for all but the last layers to 0, you should get the intended effect.

PS: We may have to think about the option to be able to pass an initialized optimizer (your 2nd approach).

**Comment by Arkoprabho** [comment]
I will give this a try and will come back if I run into any issues. Any idea about the memory usage of this? The model I am training does not fit in my GPU memory if the parameters aren't declared as non-trainable. (A ResNet152 on a GTX 1060 6GB, batch size 32)
Being able to pass an initialised optimizer will really help with fine-tuning. It is much easier to define a few layers as non-trainable and create an optimizer that works only for the non-trainable parameters than to define learning rates for the layers in the network.

**Comment by ottonemo** [comment]
>  Being able to pass an initialised optimizer will really help with fine-tuning. It is much easier to define a few layers as non-trainable and create an optimizer that works only for the non-trainable parameters than to define learning rates for the layers in the network.

It is probably helpful to be able to pass initialized optimizers but this is not a trivial change since it breaks re-initialization of the optimizer and setting optimizer parameters after initialization. It might take some time to do that right. 

In the meantime you can always overwrite `initialize_optimizer` and filter the parameters that get passed to the optimizer yourself, or, alternatively you can pass a function as optimizer that returns an optimizer instance with filtered parameters, e.g.:

```python
def filtered_optimizer(pgroups, **kwargs):
    params = filter(lambda t: t[1].requires_grad, pgroups[0]['params'])
    return torch.optim.SGD(params, **kwargs)

net = Net(module, optimizer=filtered_optimizer)
```

**Comment by BenjaminBossan** [comment]
Excluding parameters that don't require gradients should be the default, honestly. Does it ever make sense to include those?

> alternatively you can pass a function as optimizer that returns an optimizer instance with filtered parameters

Elegant solution, maybe this should be added to the FAQ (at least for as long as there is no better solution).

**Comment by Arkoprabho** [comment]
> Excluding parameters that don't require gradients should be the default, honestly. Does it ever make sense to include those?

There was an issue raised regarding this on pytorch [here](https://github.com/pytorch/pytorch/issues/679)

**Comment by ottonemo** [comment]
@thomasjpfan I like this since it is straightforward and the user has full control but I also see that this might cause problems and unwanted side effects with tools that, for example, visualise the computation graph or print the number of parameters.

**Comment by thomasjpfan** [comment]
@ottonemo Tools like https://github.com/sksq96/pytorch-summary handles frozen parameters well by outputting the number of training and non-training parameters. For example, `pytorch-summary` can output:

```
Total params: 21,840
Trainable params: 20,840
Non-trainable params: 1,000
```

I usually include a `unfreeze` function to set `requires_grad=True`, which is used when another tool needs the whole graph to be unfrozen.

**Comment by ottonemo** [comment]
@thomasjpfan I don't see how this still works when you overwrite `named_parameters` in your model. How is the external tool supposed to know how many parameters there are if you hide some of them in the only function that tells you about parameters (i.e. `named_parameters`)?

**Comment by ottonemo** [comment]
@thomasjpfan But that does not capture the parameters. They collect parameters of modules they know, e.g. they collect all `weight` attributes. But that does not generalize. IMO the only way to reliably get the parameter count is by using `named_parameters()`. Therefore I would refrain from overwriting `named_parameters`.

**Comment by thomasjpfan** [comment]
@ottonemo Good point! Looks like I am leaving my "`named_paramters` overwriting" days behind me. 😄 

In the context of skorch, how do you feel about filtering out `require_grad=False` parameters before passing in to an optimizer, by default? This may introduce too much "magic".

**Comment by ottonemo** [comment]
We should at least provide a function that filters elements with `requires_grad == False` from parameter lists and param groups. This way the above mentioned optimizer wrapper would be quite convenient and, if we decide to implement it as a feature, it would only add one additional line of code in `initialize_optimizer` (which should be simple to make overwriting easy).

**Comment by ottonemo** [comment]
I think we should close this in favor of #261.
