### ISSUE TITLE
Clean up modules:

### ISSUE THREAD

**Issue by benjamin-work** [dnouri/skorch#240]
* split net.py, since it's too long (e.g. into base.py and net.py)
* the callback test modules are currently all over the place

**Comment by benjamin-work** [comment]
Proposals for `net.py`:

* Split `net.py` into 2, one for the base and one for the derived classes. Makes more sense when the number of derived classes is low (classifier, binary classifier, regressor), is less consistent.
* Create a subfolder, analogously to callbacks, with a `base.py`, `classifier.py`, etc. Makes more sense when the number of derived classes grows larger, and is more consistent, but perhaps overkill.

Regarding the callback tests, they should mirror the module structure of callbacks.

**Comment by ottonemo** [comment]
Done with #249 and #251 merged.
