### ISSUE TITLE
skorch Dataset should save the 'device' attribute

### ISSUE THREAD

**Issue by benjamin-work** [dnouri/skorch#244]
Currently, the `device` attribute is not saved on the `Dataset` instance during [initialization](https://github.com/dnouri/skorch/blob/e566d897528156b63e7b581a164e65ce2602c970/skorch/dataset.py#L98). It should be saved.

**Comment by thomasjpfan** [comment]
`Dataset` does not use the `device` parameter anymore since PR https://github.com/dnouri/skorch/pull/232. There is a deprecation warning in the init:

https://github.com/dnouri/skorch/blob/e566d897528156b63e7b581a164e65ce2602c970/skorch/dataset.py#L102-L105

**Comment by benjamin-work** [comment]
Yes, I completely forgot.
