### ISSUE TITLE
Pass in a train dataset and a validate dataset (precompute cv split)?

### ISSUE THREAD

**Issue by spott** [dnouri/skorch#278]
Is it currently possible to pass in a train dataset *and* a validate dataset for a skorch NeuralNet?

It looks like I can pass a function that will do the split for me, but I already HAVE two datasets that I want to use, and combining them and then splitting them seems unnecessarily complicated...

**Comment by spott** [comment]
Thanks!  `train_split` seems like it would work well for me.

>With these approaches, you have to be careful when pickling your model, since it will include a reference to the data, which you typically don't want.

I'm not sure I understand this, you mean if `train_split` has a reference to the data, then it will be saved along with the rest of the net?

>The most robust solution is probably to really merge the two datasets and then later split them. Depending on your data, you could use cv=GroupKFold and pass a groups argument to fit that indicates whether your data belongs to train or validation.

This seems like it might be on the docket eventually.

Thanks!

**Comment by BenjaminBossan** [comment]
> I'm not sure I understand this, you mean if train_split has a reference to the data, then it will be saved along with the rest of the net?

I'm not completely certain but that could indeed happen. `NeuralNet` will has a reference to `train_split`, and if you define `train_split` as a function, your data will be part of the enclosing scope -- whether this would result in the data being pickled I'm not completely sure. If this happens, you can define your own train split class that is initialized with your data and implements a custom `__getstate__` method where you exclude your data from the object state.

Alternatively, you can use `net.save_params`, which will only persist the net parameters.

**Comment by spott** [comment]
Thanks!

**Comment by ottonemo** [comment]
This is addressed in #282.
