### ISSUE TITLE
Documentation for train-split doesn't match with code

### ISSUE THREAD

**Issue by spott** [dnouri/skorch#279]
In:

https://github.com/dnouri/skorch/blob/a4eae21d7409c478a05a571ac67e5f18ec996f19/skorch/net.py#L139-L143

The documentation says that the `train-split` method should return a `(X_train, X_val, y_train, y_val)` tuple, however, it appears that it should instead pass a `(X_dataset, y_dataset)` tuple, as seen in:

https://github.com/dnouri/skorch/blob/a4eae21d7409c478a05a571ac67e5f18ec996f19/skorch/net.py#L1068-L1069

**Comment by BenjaminBossan** [comment]
Your are right, we forgot to update the docstring when we made a change in `CVSplit`. Thanks.

**Comment by spott** [comment]
I can create a pull request for this, if needed.  Just let me know.

**Comment by BenjaminBossan** [comment]
> I can create a pull request for this

Yes, that would be great.

**Comment by benjamin-work** [comment]
@spott Are you working on the PR?

**Comment by spott** [comment]
@benjamin-work:

Thanks for the reminder.  I had forgotten about this.

**Comment by ottonemo** [comment]
Resolved by #293.
