### ISSUE TITLE
Better support for predefined splits

### ISSUE THREAD

**Issue by benjamin-work** [dnouri/skorch#282]
Addresses concerns raised in #278 and #281 

When users already have data that is split into train and validation, it is currently difficult to make skorch use those without resorting to hacks.

A possible solution is to have a class that can be passed to `train_split` and returns the predefined split. It could look somewhat like this:

```python
class PredefinedSplit:
    def __init__(self, dataset_valid):
        self.dataset_valid = dataset_valid

    def __call__(self, dataset, y=None, groups=None):
        if self.dataset_valid is None:
            raise ValueErrror("some useful message")
        return dataset, self.dataset_valid

    def __getstate__(self):
        state = self.__dict__.copy()
        state['dataset_valid'] = None
        return state
```

Apart from the question whether there could be another, better solution, those are some concerns:

* What to do when my predefined split data is not in a `DataSet`?
* What to do when persisting the split -- just discard the validation data?

**Comment by thomasjpfan** [comment]
Another approach would be:

```python
class TrainValidDataset(torch.utils.data.Dataset):
    def __init__(self, train_ds, valid_ds):
        self.train_ds = train_ds
        self.valid_ds = valid_ds

def train_valid_split(ds, y, **kwargs):
    return ds.train_ds, ds.valid_ds

train_valid_ds = TrainValidDataset(train_ds, val_ds)

net = NeuralNetClassifier(..., train_split=train_valid_split)
net.fit(train_valid_ds, y=None)
```

This keeps all the data in the `train_valid_ds` object. Thus `net` does not need to worry about state.

If `TrainValidDataset` is provided in `skorch`, we can automatically do this in `NeutralNet.get_split_datasets`:

```python
def get_split_datasets(self, X, y=None, **fit_params):
    dataset = self.get_dataset(X, y)
    if isinstance(X, TrainValidDataset):
        dataset_train, dataset_valid = X.train_ds, X.valid_ds
    ...
```

**Comment by taketwo** [comment]
@benjamin-work  This solution feels strange. The user will have to specify the validation dataset as a part of `NeuralNet` instantiation, whereas the train dataset is given to the `fit()` call.

@thomasjpfan This solution feels better. Do we even need `train_valid_split` function?

**Comment by thomasjpfan** [comment]
If we were to update `get_split_datasets`, then `train_valid_split` is not needed. I updated the comment to address this.

**Comment by benjamin-work** [comment]
> The user will have to specify the validation dataset as a part of NeuralNet instantiation, whereas the train dataset is given to the fit() call

This is one of the reasons why we did not choose this is the default way of doing things.

I also like @thomasjpfan's solution but it probably needs some work still. E.g. `TrainValidDataset`, despite wrapping datasets, is not a `torch.utils.data.Dataset` because it does not implement `__len__` and `__getitem__`. So either we drop this inheritance and add support for this new data type or we have an object that pretends to be a `Dataset` but isn't, which could cause trouble down the line.

**Comment by thomasjpfan** [comment]
We can extend `TrainValidDataset` to support the full `torch.utils.data.Dataset` interface:

```python
class TrainValidDataset(torch.utils.data.Dataset):
    def __init__(self, train_ds, valid_ds):
        self.train_ds = train_ds
        self.valid_ds = valid_ds

    def __len__(self):
        return len(self.train_ds) + len(self.valid_ds)

    def __getitem__(self, i):
        if i < len(self.train_ds):
            return self.train_ds[i]
        i = i - len(self.train_ds)
        return self.valid_ds[i]
```

**Comment by taketwo** [comment]
While implementing the full `Dataset` interface is possible, does this add any value? From my perspective, `TrainValidDataset` is a thin container for the two datasets. It can be created on-the-fly, just for the `fit()` call:

```python
net.fit(TrainValidDataset(train_ds, val_ds))
```

And it only needs to live until the `get_split_datasets()` tears it apart. In fact, a tuple could do this job, but unfortunately we can not use a plain tuple (`X` can itself be a tuple, so there would be no way to differentiate).

**Comment by thomasjpfan** [comment]
The only reason to subclass `torch.utils.data.Dataset` is to make sure `NeutralNet.get_dataset` returns `X` without modifying it. We can update `skorch.utils.is_dataset` to return true for `TrainValidDataset`. This would allow `TrainValidDataset` to not need to be a `torch.utils.data.Dataset` subclass.

**Comment by BenjaminBossan** [comment]
I commented on @thomasjpfan's proposal in the PR.

I agree that having `TrainValidDataset` be a dataset just so that we save a check later in the code is not a sufficient reason. Still, I would like to discuss another proposal. Say we introduce a dataset class as shown above (maybe inherit from `skorch.dataset.Dataset`) and add a utility function where I can pass my pre-existing split data and get this dataset back, as well as a `CVSplit` that splits the data again. It would look like this:

```
ds_train, ds_valid = ...
ds_all, train_split = merge_split_data(ds_train, ds_valid)  # need better name
net = NeuralNet(..., train_split=train_split)
net.fit(ds_all)
```

`ds_all` would be a dataset of the type shown above and `merge_split_data` would be something like this:

```
der merge_split_data(ds_train, ds_valid):
    ds_all = TrainValidDataset(ds_train, ds_valid)
    test_fold = [1] * len(ds_train) + [0] * len(ds_valid)
    train_split = CVSplit(sklearn.model_selection.PredefinedSplit(test_fold))
    return ds_all, train_split
```

Maybe `merge_split_data` can be even written in a way that works with other data types.

This proposal would address some of my concerns mentioned in #283. What do you think?

**Comment by thomasjpfan** [comment]
I can see opening up `merge_split_data` to allow for the other supported data types:

```
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

ds_all, train_split = merge_split_data(
    X_train, X_test, y_train, y_test)

net = NeuralNet(..., train_split=train_split)
net.fit(ds_all)
```

My concern with `merge_split_data` is that it couples the data with the initialization of `NeutralNet`. This is why I choose to ignore `Neutral.train_split` when using `TrainValidDataset` in my PR.

**Comment by ottonemo** [comment]
I think that having two ways of defining splits is confusing and I don't see a good way of removing the `train_split` parameter if we want support for pipelines and model selection utilities. Additionally, I am not yet convinced that we do have a problem that needs additional data structures or changes in the way input data is handled.

A while back in https://github.com/dnouri/skorch/issues/146#issuecomment-363808856 we discussed a helper function that defines a simple predefined dataset split. Today this would look something like this:

```python
# in skorch.helper
def split(a, b): return a, b
def predefined_split(ds_valid): return partial(split, b=ds_valid)

Net(train_split=predefined_split(ds_valid))
``` 

This function should be pickle-able since it is basically just a partial with a reference to a named function and allows for convenient application of a validation dataset. If the user does not have a dataset at hand, creating the dataset is quite simple using the `skorch.Dataset(X, y)` constructor.

**Comment by benjamin-work** [comment]
If we have consensus on this, those would be the TODOs:

- [ ] implement the functions in `utils.py` (maybe find a better name than `split`)
- [ ] add a section to FAQ that describes how to use `predefined_split` (incl. with non-dataset data)
- [ ] update docs/docstring where applicable

**Comment by thomasjpfan** [comment]
I am okay with `predefined_split`. I will work on its implementation/docs.

**Comment by benjamin-work** [comment]
Great, thank you very much.

**Comment by taketwo** [comment]
I'd give `split()` a different name because on its own it has nothing to do with splitting.

```python
def split(a, b): return a, b
```

is an identity function

**Comment by ottonemo** [comment]
A private
```python
def _tuple2(t1, t2): return t1, t2
```
or public
```python
def train_valid_dataset_pair(train_ds, valid_ds): return train_ds, valid_ds
```
would work for me but I don't have a strong opinion about this.

**Comment by Tsakunelson** [comment]
> We can extend `TrainValidDataset` to support the full `torch.utils.data.Dataset` interface:
> 
> ```python
> class TrainValidDataset(torch.utils.data.Dataset):
>     def __init__(self, train_ds, valid_ds):
>         self.train_ds = train_ds
>         self.valid_ds = valid_ds
> 
>     def __len__(self):
>         return len(self.train_ds) + len(self.valid_ds)
> 
>     def __getitem__(self, i):
>         if i < len(self.train_ds):
>             return self.train_ds[i]
>         i = i - len(self.train_ds)
>         return self.valid_ds[i]
> ```
Hello @thomasjpfan I attempted applying this procedure for K-fold CV with torch ImageFolder datasets, but ran into a TypeError with the following stack trace:
![image](https://user-images.githubusercontent.com/17685437/53927855-1b3f2900-4056-11e9-940e-c437b408a5ce.png)

Here is the code sample:
```
data = load_data.load('./poorly_cohessive/ck_dataset')
train_ds, valid_ds = data[0], data[1]

net = NeuralNetClassifier(
    PretrainedModel,
    criterion=nn.CrossEntropyLoss,
    lr=0.001,
    batch_size=32,
    max_epochs=25,
    module__output_features=2,
    optimizer=optim.SGD,
    optimizer__momentum=0.9,
    iterator_train__shuffle=True,
    iterator_train__num_workers=4,
    iterator_valid__shuffle=True,
    iterator_valid__num_workers=4,
    train_split=CVSplit(PredefinedSplit(valid_ds)),
    callbacks=[lrscheduler, checkpoint, freezer],
    device='cuda' # comment to train on cpu
)
from sklearn.model_selection import GridSearchCV
params = {
    'lr': [0.01, 0.02],
    'max_epochs': [10, 20]
    #'module__num_units': [10, 20],
}
gs = GridSearchCV(net, params, refit=False, cv=5, scoring='accuracy')
gs.fit(train_ds, y=None)
print(gs.best_score_, gs.best_params_)
```
Did I miss any other information? I am quite new to Skorch. Feedback much appreciated.
I sent you a tweet on this :)

**Comment by thomasjpfan** [comment]
Gridsearch does not work with pytorch's dataset object, can you open up a new issue on this?
