### ISSUE TITLE
Doc build is failing

### ISSUE THREAD

**Issue by taketwo** [dnouri/skorch#304]
I've just noticed that the doc badge is red. I tried to look around, but couldn't find a way to check the build log and figure what's wrong and since when.

**Comment by thomasjpfan** [comment]
Here is the error: https://readthedocs.org/projects/skorch/builds/7580840/

Here are all the doc builds: https://readthedocs.org/projects/skorch/builds/

**Comment by taketwo** [comment]
So the problem is with the installation of pytorch 0.4.1.

**Comment by benjamin-work** [comment]
But is it? pytorch does not appear in the requirements.txt.

**Comment by taketwo** [comment]
Have a look at the first failed build: https://readthedocs.org/projects/skorch/builds/7574065/

```
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    torch==0.4.1 from https://files.pythonhosted.org/packages/f9/4e/1bcb4688b7506c340ca6ba5b9f57f4ad3b59a193bba365bf2b51e9e4bb3e/torch-0.4.1-cp35-cp35m-manylinux1_x86_64.whl#sha256=725ae85be70a569583863c263e281938b21e5e92d9a8f480094555b59a82936d (from -r docs/requirements.txt (line 2)):
        Expected sha256 725ae85be70a569583863c263e281938b21e5e92d9a8f480094555b59a82936d
             Got        dfcbd58955bc14b7548a1fa5390696559a4997f793ca263259c79bd37d84e014
```

**Comment by benjamin-work** [comment]
It does not seem that anything will be done from the [PyTorch side](https://github.com/pytorch/pytorch/issues/1022), so those are the options I can think of:

* wait and hope that this solves itself
* mock torch
* increase the limit for RTD (idk if that is possible)
* install the smallest wheel

None of this sounds particularly attractive.

**Comment by taketwo** [comment]
Strange, I wried to `wget` the file in question `https://files.pythonhosted.org/packages/f9/4e/1bcb4688b7506c340ca6ba5b9f57f4ad3b59a193bba365bf2b51e9e4bb3e/torch-0.4.1-cp35-cp35m-manylinux1_x86_64.whl` and compute SHA256. I get the _expected_ hash.

**Comment by taketwo** [comment]
[This](https://stackoverflow.com/a/40184923/1525865) suggests that we can try to `pip install` with `--no-cache-dir` option. But to be honest, I'm not familiar with how RTD works. Do we have control over the documentation build process?
