### ISSUE TITLE
Refactor ProgressBar

### ISSUE THREAD

**Issue by benjamin-work** [dnouri/skorch#319]
This class could benefit from some small refactorings.

For instance, it overrides the `batches_per_epoch` attribute when it is `'count'`, which contradicts the policy to never change init params. It is also surprising that `'count'` triggers the estimation only once per fit call, whereas `'auto'` does it once per epoch.

This refactoring should also include more rigorous unit tests that control the inferred batch size in `'count'` and `'auto'` mode. To facilitate this unit test, there could be a public function that derives the batch size from a dataset:

```
def estimate_batches_per_epoch(dataset, batches_per_epoch='auto'):
    if isinstance(batches_per_epoch, int):
        return batches_per_epoch
    if batches_per_epoch == 'count':
        return None
    ...
```

**Comment by benjamin-work** [comment]
I'm not totally sure but I believe the comment is meant to imply that because the batch size is 10 and the number of samples is 20, there is a nice split with exactly 2 batches per epoch. Of course, this assumes that there is no train/valid split, but since there is, the observed pattern of 16/4 emerges.

If my interpretation is correct, your change in #326  should lead to the correct result.

**Comment by taketwo** [comment]
Yes, it's ready now.
