### ISSUE TITLE
Working with PackedSequence issues

### ISSUE THREAD

**Issue by Naffer11** [dnouri/skorch#325]
Firstly I'd like to thank you for the great job you have done with skorch - I've found it very useful!
However, I have 2 observations.

Lately, while I've been trying to work with sequence data with a varying length I decided to use PackedSequence data from torch.
The first thing that is easy to fix is the to_tensor function from skorch.utility - although it's docstring states it supports PackedSequence, as this class is a namedtuple under the hood, it is also an instance of a tuple, and as so the PackedSequence is being handled as a tuple.

```
import torch

seq = [torch.rand(4,1) for _ in range(5)]
pack_seq = torch.nn.utils.rnn.pack_sequence(seq)

print(isinstance(pack_seq, tuple))
print(isinstance(pack_seq, torch.nn.utils.rnn.PackedSequence)
```
This can be easily fixed moving more specific condition of being a PackedSequence before the condition of being a tuple.

The second thing is more of a thought on handling a varying length data by skorch - the most convenient way I found to handle it by Pytorch is by using a list of Tensors and then converting it to mentioned earlier PackedSequence. The problem arises with the all the internal skorch lenght checking functions - they rise error when the data have inconsistent lenght, what is an expected situation sometimes like when dealing with varying length sequences. I managed to overwrite all the places where it is done ( in Dataset __init__(), in CVSplit __call__() and NeuralNet in fit_loop()) because they all call skorch.utils.get_len() the function which unpacks the data to check the lengths - as this function is defined in the package directory there is no other way than overriding all the functions that call it to change its default behaviour.
I was wondering do you think it would be possible to:
a) give an option to pass on checking the length in all listed structures by one parameter (something like check_len =False)
b) enable the user to pass a function responsible for checking the lenghts of passed structures
I think the second option is much more elegant, but I am not sure how it could be best done.

Hope I described clearly my points if anything is unclear I can provide more details if needed.

**Comment by BenjaminBossan** [comment]
Thank you for using skorch.

Regarding your first point, I will look at it on Monday. If you think you know how to fix that, I also invite you to make a PR.

Regarding your second point, do I get it right that you pass your proper data and your array of lengths as a list and then get problems because the list does not have the same length as your `y` data? If so, I would recommend you pass your data as a dictionary:

```
class MyModule(nn.Module):
    ...
    def forward(self, X, lengths):  # dictionary keys are passed as keyword arguments
        ....

X = {'X': data, 'lenghts': lengths}
```

This is should get you the correct behavior as long as `data`, `lengths` and `y` have the same `len`. If you mean something else, could you please elaborate or post a minimal code example?

**Comment by benjamin-work** [comment]
@Naffer11 Did you make progress?

**Comment by Naffer11** [comment]
Hey,
thanks for such fast reply, and sorry for not responding before.
It may be my mistake to put separate thoughts into one issue. Saw your PR #335, and although I had in mind some other solution, this seem to be much more elegant! I think it will fix my issue, and I in some free time I will try to open a separate issue for the second thought I had, with the reproducible example.
