### ISSUE TITLE
Compatibility with python 3.5 and 3.7

### ISSUE THREAD

**Issue by ottonemo** [dnouri/skorch#333]
PR #331 fixes an issue with python 3.5 dict ordering. There are additional test errors with python 3.5 which should be fixed (it is the default python version on Ubuntu 16.04). When doing this we should also test python version 3.7. Additionally we should think about testing different python versions directly (e.g. using Travis).

**Comment by benjamin-work** [comment]
Those are the issues I found with Python 3.5:

* `PosixPath` does not work with `open` (only [changed](https://docs.python.org/3/whatsnew/3.6.html#pep-519-adding-a-file-system-path-protocol) in 3.6).
* The test for the error message [here](https://github.com/dnouri/skorch/blob/d27da20ed7a7b14f31026df3ce6f8a9baba8914c/skorch/net.py#L257) depends on dictionary order, the solution is probably to sort the `unexpected_kwargs` before passing them to the error message.

**Comment by ottonemo** [comment]
We are explicitly testing for python 3.5, 3.6 and 3.7 so any issues should get detected.
