### ISSUE TITLE
More than one Checkpoint

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [dnouri/skorch#338]
Hi,

Is it possible to add more than one Checkpoint to store different models based on different metric?

e.g.
```
net = NeuralNet(callbacks=[Checkpoint(monitor=loss_monitor), Checkpoint(monitor=accuracy_monitor)....])
```
Thank you

**Comment by ottonemo** [comment]
Since this is easily possibly and there does not seem to be an issue, I'm closing this.
