### ISSUE TITLE
How are you supposed to use the WarmRestartLR?

### ISSUE THREAD

**Issue by spott** [dnouri/skorch#348]
As a first argument, it takes an optimizer.  But the optimizer isn't available when you initialize the skorch network.

Are you supposed to break out the network definition, and the optimizer in order to use this?

**Comment by ottonemo** [comment]
No the `WarmRestartLR` is just a policy for the `LRScheduler` callback written to be compatible with how PyTorch implements learn rate policies.

To use `WarmRestartLR`, just pass `policy='WarmRestartLR'` when instantiating `skorch.callbacks.LRScheduler`, this is also the default policy (see the [docs](https://skorch.readthedocs.io/en/latest/callbacks.html#skorch.callbacks.LRScheduler)):

```python
net = Net(mod, callbacks=[
    skorch.callbacks.LRScheduler(policy='WarmRestartLR'),
])
```

**Comment by benjamin-work** [comment]
I have to agree, though, that it's not obvious from the start and maybe an example in the docstring might be helpful.

**Comment by BenjaminBossan** [comment]
@spott Did this solve your issue?

**Comment by spott** [comment]
Yes.
