### ISSUE TITLE
Use travis-ci to deploy on tagged commits

### ISSUE THREAD

**Issue by thomasjpfan** [dnouri/skorch#353]
We can use travis-ci to deploy skorch on tagged commits. 

1. This may help with https://github.com/dnouri/skorch/issues/129, since we can pin down the environment that is deploying the README.
2. Using travis ci to deploy releases would reduce friction in deployment, which may enable us to deploy minor releases with bug fixes quicker.

For reference, here is documentation on how to do a travis ci deployment on pypi: https://docs.travis-ci.com/user/deployment/pypi/

**Comment by thomasjpfan** [comment]
I think a increased deployment cycle would help iron out bugs in skorch, because there would be more users using the latest features in their workflows. A automated deployment would make it easier to deploy minor releases for bug fixes.

Deploy dependencies, like `twine`, could have their versions pinned down. Additionally, the deploy environment would be standardized to using travis, which makes it easier to debug issues with deployment. (including the README)

**Comment by ottonemo** [comment]
I'm against *automatically* deploying new releases but I'm all for automating most of the process and making it generally easier to release. With the new `CHANGES.md` one of the worst pain points during release should be gone (writing the change list). What needs to be done now is to create an environment for the deployment tools (i.e. twine et al.) and put everything in a Makefile (or similar) so deploying is as easy as running `conda activate skorch_deploy && make deploy`.
