### ISSUE TITLE
Add an easy way to save and load the optimizer

### ISSUE THREAD

**Issue by benjamin-work** [dnouri/skorch#357]
Some optimizers are stateful. When just using `save_params`, this state is lost. We should either add a possibility to save the parameters of the optimizer in a specific method, or adjust `save_params` so that optimizer state is included.

Note that this will also affect `Checkpoint`.

**Comment by thomasjpfan** [comment]
For reference, the state of an optimizer is defined here: https://github.com/pytorch/pytorch/blob/28e1571843f1b12e933e789ddcbf54339c92e24d/torch/optim/optimizer.py#L11. Subclasses of `Optimizer` may have more states.

In general, all optimizers contains `param_groups` that references to `Tensors`. This may make it harder to use `save_params` to store the state.

Given that all the optimizers define `__getstate__` and `__setstate__`, it feels like pytorch prefers using pickle to save these classes.

**Comment by benjamin-work** [comment]
> In general, all optimizers contains `param_groups` that references to `Tensors`. This may make it harder to use `save_params` to store the state.

I think that should not be a problem since the tensors are referencing the same objects as the `module_` parameters, so if we were to save them together in a data structure, they shouldn't be saved twice (or did you mean another problem?).

On the other hand, optimizers also have a `state` attribute that can be quite large for some. I can imagine that not everybody needs this, so we shouldn't make it mandatory.

Overall, I believe that changing `save_params` to include optimizer state (and possibly even more state if it becomes necessary) is possible:

```
def save_params(self, f):
    ...
    state_dict = {'module': self.module_.state_dict, 'optimizer': self.optimizer_.state_dict}
    # pickle results
```
The problem, though, is that this new `state_dict` is not directly compatible with torch, i.e. I cannot just use `torch.load`, and I would *really* like to avoid having a skorch-specific data format. Therefore, I would prefer a way that sticks as closely to torch as possible. What are the best practices there for saving and loading when the optimizer has state?

**Comment by thomasjpfan** [comment]
`ignite` uses `torch.save(optimizer, path)`, which pickles the optimizer. It also gives the user the option to save the state_dict: `torch.save(optimizer.state_dict(), path)`. They save the module and optimizer into two separate files, which the users specifies.

For our use case we could change `save_params` to accept three paths

```python
def save_params(self, model_f, optimizer_f=None, history_f=None):
    ...

def load_params(self, model_f, optimizer_f=None, history_f=None):
    ...
```

And allow the user specify where to save the optimizer and the history all at once. This would save most of the state of a neutral network that changes during training.

**Comment by benjamin-work** [comment]
All these disparate files look a little bit unwieldy but I see no other way (short of pickling the whole net).

Regarding parameter names, I would like to stay consistent with `Checkpoint`, i.e. using `f_params` and `f_history` and adding `f_optimizer`.
However, if we choose `f_params`, it would be a backward-incompatible change because the current name is just `f`. Maybe that's okay because most people will probably use it as a positional argument, but I could also see leaving the name as is or allowing both while deprecating `f`.
