### ISSUE TITLE
Strange fitting behaviour between nn.Sequential and nn.Module with NeuralNet

### ISSUE THREAD

**Issue by trias702** [dnouri/skorch#376]
Hello,

I'm quite excited about Skorch and loving how easily it can wrap Pytorch models, but in evaluating it for doing different tasks, I've noticed that the NeuralNet wrapper seems to have radically different fit convergence between feeding a nn.Sequential model to NeuralNet vs feeding an nn.Module class. I will outline my code below to show you this behaviour as I am seeing it.

```
ann_sequential_scores = []
ann_class_scores = []
N_EPOCHS = 20
```

Now for the Sequential model:
```
ann_model = nn.Sequential(
    nn.Linear(x_train_tfidf.shape[1], 256),
    nn.ELU(),
    nn.BatchNorm1d(256, momentum=0.99),
    nn.Dropout(0.5),
    nn.Linear(256, 256),
    nn.ELU(),
    nn.BatchNorm1d(256, momentum=0.99),
    nn.Dropout(0.5),
    nn.Linear(256, NCLASSES),
    nn.Sigmoid()
)

def init_weights(m):
    if type(m) == nn.Linear:
        torch.nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')

ann_model.apply(init_weights)
```

We then do a complete fit from scratch on this model, N_EPOCHS number of times, and after each fit, append the MAE for that fit:
```
for i in range(N_EPOCHS):
    model = NeuralNet(ann_model, max_epochs=20, lr=0.01, batch_size=32, train_split=None,
                                optimizer=optim.RMSprop,
                                criterion=nn.L1Loss,
                                criterion__reduction='sum',
                                device='cuda',
                                iterator_train__shuffle=True,
    
    model.fit(x_train_tfidf, y_train.astype(np.float32))

    pred_label = model.predict(x_test_tfidf)

    ann_sequential_scores.append( mean_absolute_error(y_test, pred_label) )
    
    del model
```

Now we execute the same loop, but this time we use an identical model, but as a class which derives from nn.Module:
```
class ANNModel(nn.Module):
    def __init__(self, input_size, neurons, nclasses):
        super(ANNModel, self).__init__()
        
        self.h1 = nn.Linear(input_size, neurons)
        self.bn1 = nn.BatchNorm1d(neurons, momentum=0.99)
        self.h2 = nn.Linear(neurons, neurons)
        self.bn2 = nn.BatchNorm1d(neurons, momentum=0.99)
        self.out = nn.Linear(neurons, nclasses)
                
        torch.nn.init.kaiming_normal_(self.h1.weight, mode='fan_out', nonlinearity='relu')
        torch.nn.init.kaiming_normal_(self.h2.weight, mode='fan_out', nonlinearity='relu')
        torch.nn.init.kaiming_normal_(self.out.weight, mode='fan_out', nonlinearity='relu')                
        
    def forward(self, x):
        x = F.elu(self.h1(x))
        x = F.dropout(self.bn1(x), p=0.5)
        x = F.elu(self.h2(x))
        x = F.dropout(self.bn2(x), p=0.5)
        output = F.sigmoid(self.out(x))
        
        return output
```

We now use an identical loop to fit N_EPOCHS number of times, each time appending the MAE:
```
for i in range(N_EPOCHS):
    model = NeuralNet(ANNModel, max_epochs=20, lr=0.01, batch_size=32, train_split=None,
                            module__input_size=x_train_tfidf.shape[1],
                            module__neurons=256,
                            module__nclasses=NCLASSES,
                            optimizer=optim.RMSprop,
                            criterion=nn.L1Loss,
                            criterion__reduction='sum',
                            device='cuda',
                            iterator_train__shuffle=True,

    model.fit(x_train_tfidf, y_train.astype(np.float32))
    
    pred_label = model.predict(x_test_tfidf)

    ann_class_scores.append( mean_absolute_error(y_test, pred_label) )
    
    del model
```

After running both of these code blocks, I compare the mean of their respective mae storage arrays, and they are quite different, at 0.85 for the Sequential model, and 1.06 for the Module class model. I get these same means (+/- 0.03) after restarting the kernel and re-running. I've done this about 10 times in all, and every time I'm getting the same means.

I'm not sure I understand why this is happening. I know that the skorch NeuralNet class can handle an already instantiated model, such as Sequential, or a class model which is uninstantiated. But their convergences seem to be quite a bit different.

Is there something substantially different happening under the hood in NeuralNet for instantiated vs. uninstantiated models?

Environment: Windows 10 x64
Pytorch version: 0.4.1
Skorch version: 0.4.0
Python version: 3.6.6

**Comment by githubnemo** [comment]
skorch will not re-initialize your model when it is already instantiated. Therefore in the one loop where you use `ann_model` you train the same model for `N_EPOCHS` times as skorch leaves your instantiated model alone. In the second loop you train a new model every time you call `fit`, since you just pass the model class and skorch builds the model anew every time.

**Comment by trias702** [comment]
Thanks very much for the clarification! I had thought of this issue before, but in reading your official Skorch FAQ, I was confused by this point:

> By default, when you call fit() more than once, the training starts from zero instead of from where it was left. This is in line with sklearn’s behavior but not always desired. If you would like to continue training, use partial_fit() instead of fit().

So I assumed that calling .fit() on ann_model, somehow reset the model parameters back to truncated normal or similar.

So two questions then:

- in my original example, where I pass the instantiated nn.Sequential model, what is the best way to "reset" it back to all random weights/biases in between iterations of the outer for (N_EPOCHS) loop?

- could you please explain what you mean by your FAQ which says "By default, when you call fit() more than once, the training starts from zero". What do you mean by "from zero" in this context?

**Comment by githubnemo** [comment]
I see how this can be confusing but the general rule is that skorch will attempt to not touch an initialized model instance unless it absolute has to (e.g., the user wants to set model parameters, this is currently only possible by re-initializing the model). The re-initialization argument from the FAQ is actually for the more common case in which you pass the model **class** to skorch. In that case, `fit` will always re-initialize the model and `partial_fit` won't after the network is initialized once.

To address your questions,

> in my original example, where I pass the instantiated `nn.Sequential` model, what is the best way to "reset" it back to all random weights/biases in between iterations of the outer for (`N_EPOCHS`) loop?

In this case you are the only person who knows! When passing a model instance, skorch can't possibly know what to do with your model when it needs resetting since it does not know about possible modifications you have done, therefore skorch doesn't touch it. What you can do is to add your
to the beginning of the loop and call it before creating the network instance:
```python
for i in range(N_EPOCHS):
    ann_model.apply(init_weights)
    model = NeuralNet(ann_model, max_epochs=20, lr=0.01, batch_size=32, train_split=None,
    # [...]
```

> could you please explain what you mean by your FAQ which says "By default, when you call fit() more than once, the training starts from zero". What do you mean by "from zero" in this context?

As I explained above, normally (i.e. in the case when you pass a model class to skorch) the model will be re-initialized on every call to `fit()`. Therefore "from zero" means that the model will have the state that it has after initialization, e.g. the same state you get when you execute `model = ANNModel()`.

**Comment by BenjaminBossan** [comment]
Good explanation. I agree that the documentation could be more precise. We should add a condensed form of the explanation above to the docs and possibly the FAQ.

**Comment by trias702** [comment]
Thank you very much for the clear explanations, I now understand everything perfectly and will adjust my code and re-run my tests.

Just also want to take a moment and say how much I love Skorch and really appreciate all of the work you put into it, it's very well designed and actually makes Pytorch usable in a corporate environment (as our team does not have the time to write a fitting loop from scratch for each new project, and Skorch accomplishes exactly what we need -- fast, reusable boilerplate code for fitting/predicting/saving, just like Keras has)

**Comment by ottonemo** [comment]
This issue was resolved and the task to update documentation will be continued in #409.
