### ISSUE TITLE
Does Sktorch work with Auto-sklearn, tpot and featuretools ?

### ISSUE THREAD

**Issue by truongtamgio** [dnouri/skorch#386]
Hello,
I want to ask that whether Sktorch work well with Auto-sklearn, tpot and featuretools ? Thank you !

**Comment by benjamin-work** [comment]
I personally have not tried skorch with any of the mentioned libraries. However, a main goal of skorch is that it provides an sklearn-compatible interface. Therefore, if the libraries work with sklearn estimators, they should work with skorch. I would thus suggest to simply try them out and to report any issue you encounter.
