### ISSUE TITLE
Impossible to use Scoring callback for existing values

### ISSUE THREAD

**Issue by ottonemo** [dnouri/skorch#52]
I already computed scores in my loss function and now I want to score them so that I can print them per epoch. For example:

    class MyNet(NeuralNetwork):
        def get_loss(...):
            self.history.record_batch('foo', 42)

     net = MyNet(callbacks=[
         inferno.callbacks.Scoring('foo'),
     ])

However, the `Scoring` callback calls its `score` method on each batch end and overwrites the value `"foo"` and there is no way to properly disable this behavior. 

There is a workaround though (but an ugly one):

    def ignore_scorer(*_): raise KeyError()

    net = MyNet(callbacks=[
         inferno.callbacks.Scoring('foo', scoring=ignore_scorer),
     ])

We should cover this case.

**Comment by benjamin-work** [comment]
Look at the current implementation for "train_loss"/"valid_loss":

```
def train_loss_score(net, X=None, y=None):
    return net.history[-1, 'batches', -1, 'train_loss']

def valid_loss_score(net, X=None, y=None):
    return net.history[-1, 'batches', -1, 'valid_loss']

class NeuralNet:
    ...
    default_callbacks = [
        ...,
        ('train_loss', Scoring('train_loss', train_loss_score, on_train=True)),
        ('valid_loss', Scoring('valid_loss', valid_loss_score)),
        ...,
    ],
```

Its not the most beautiful solution, but it avoids calculating anything twice while allowing to use `Scoring`.

**Comment by ottonemo** [comment]
Yep, works fine. We should provide an example in the documentation of `Scoring` though.
