### ISSUE TITLE
Remove ugly solution to 1-dim target data problem

### ISSUE THREAD

**Issue by benjamin-work** [dnouri/skorch#65]
We have some ugly pieces of code that are necessary to make our code work with `default_collate`. They relate to the probem that `default_collate` picks out values one at a time, which makes it hard to work with 1-dim arrays (e.g. to cast them to cuda).

The corresponding pieces of code are:
* [`_prepare_target_for_loss`](https://github.com/dnouri/inferno/blob/ae5f977f87751b30dd7b4b863a294de69927b634/inferno/net.py#L926)
* The [y dimensionality check](https://github.com/dnouri/inferno/blob/ae5f977f87751b30dd7b4b863a294de69927b634/inferno/net.py#L985) in `NeuralNetRegressor`

**Comment by ottonemo** [comment]
This has been resolved in #185 and the introduction of scalars in PyTorch.
