### ISSUE TITLE
Improve attributes and methods section in docs

### ISSUE THREAD

**Issue by benjamin-work** [dnouri/skorch#97]
- [ ] Currently, no line breaks -> very long lines
- [x] Methods are not linked

**Comment by ottonemo** [comment]
Is this still something we would want to do before releasing 0.2.0?

**Comment by benjamin-work** [comment]
I'm fine with leaving it open for now

**Comment by taketwo** [comment]
@benjamin-work Not clear what exactly you were referring to here. Is this perhaps fixed with #213 and #242? Or if not, please point me where the issues are and I'll send another PR.

**Comment by benjamin-work** [comment]
The issue with the links on methods seems to be fixed.

Regarding the long lines: Look [here](https://skorch.readthedocs.io/en/latest/callbacks.html) at the **Methods** section. At the top, there is a table that lists all methods with their docstrings but without line breaks. Below, the methods are described again in a more readable fashion. I believe the table should be removed.

**Comment by taketwo** [comment]
The table lists all the methods, including inherited. This may be useful to get a quick overview of __all__ what a particular class has to offer. (Although the inherited methods are not hyperlinked, this makes it far less useful.)

The lack of line breaks is inconvenient, however it feels like the true issue is that the function names include arguments. This makes the first column too long, leaving very little space for the second. I think if this was corrected, then almost all docstrings would fit without scrolling. (And arguably those that don't fit should be simplified to be more concise.)

That being said, it seems like we anyway have no control over any of these with [automodule](http://www.sphinx-doc.org/en/master/ext/autodoc.html#directive-automodule) directive.

One option would be to ditch `automodule` and compose documentation in a semi-automatic way (e.g. list classes and methods explicitly, but let `automethod` add docstrings). This is how PyTorch does it. I'm not sure how desirable this is given that it complicates maintenance.

**Comment by benjamin-work** [comment]
Overall, these deficits in the docs are not a huge issue, if it takes too much work to mend them, then it's better to let it be.

> the function names include arguments

If that could be fixed, we would already gain a lot.

> those that don't fit should be simplified to be more concise

We should consider this. Are there any standards on how long the first part should be?

**Comment by taketwo** [comment]
> If that could be fixed, we would already gain a lot.

Again, no option is exposed to control that. Perhaps we can inject some javascript in the page template that would hide the arguments inside summary tables. If this is something you may consider, I can explore this possibility.

> Are there any standards on how long the first part should be?

[PEP 257](https://www.python.org/dev/peps/pep-0257/) suggests one line:

> The summary line may be used by automatic indexing tools; it is important that it fits on one line.

So does [Google style guide](https://google.github.io/styleguide/pyguide.html?showone=Comments#Comments):

> A doc string should be organized as a summary line (one physical line) terminated by a period

... and [NumPy style guide](https://numpydoc.readthedocs.io/en/latest/format.html):

> A one-line summary that does not use variable names or the function name, e.g.

By the way, NumPy style (which skorch probably should follow being a part of scikit family) stipulates 75 characters long docstrings. From my observations, skorch docstrings seems to be formatted for 70 characters width.

**Comment by BenjaminBossan** [comment]
> The summary line may be used by automatic indexing tools; it is important that it fits on one line.

This is an ideal that is probably hard to keep up with in practice, but we should try.

> skorch docstrings seems to be formatted for 70 characters width.

I believe this is something we don't enforce consciously yet. 

In general, we may consider using [black](https://github.com/ambv/black) in the future for code formatting, once it becomes stable, especially since our code is mostly compliant anyway. However, I didn't see anything about line length in docstrings.

> If this is something you may consider, I can explore this possibility.

I believe we have more urgent things to do at the moment. And I wouldn't want to be the one debugging javascript if it were to fail one day ;)

**Comment by taketwo** [comment]
FWIW, this one-liner removes the arguments:

```javascript
$('dl.class table.longtable.docutils td:first-child').contents().filter(function(){return this.nodeType === 3;}).remove()
```

Of course, this will break if Sphinx decides to change CSS class names, so I understand your reluctance to integrate a fix of this kind.

I suppose there are no actionable items in this issue then (besides from perhaps branching out another issue for future code formatting).

**Comment by ottonemo** [comment]
We linked most of the methods and decided that line breaks are not an issue important enough to leave this ticket open.
